# Generated by Django 5.2.9 on 2025-12-10 16:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Трек-номер должен содержать от 1 до 20 цифр.', regex='^\\d{1,20}$')], verbose_name='Трек-номер')),
                ('status', models.IntegerField(choices=[(0, 'Ожидает поступления на склад в Китае'), (1, 'Принят на склад в Китае'), (2, 'Отправлен из Китая'), (3, 'Прибыл в пункт выдачи'), (4, 'Получен')], default=0, verbose_name='Статус')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('last_status_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего обновления статуса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Посылка',
                'verbose_name_plural': 'Посылки',
                'ordering': ['-created_at'],
            },
        ),
    ]
