# Generated by Django 5.2.9 on 2025-12-10 16:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_parcel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='description',
            field=models.CharField(blank=True, help_text='Необязательное описание посылки', max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='last_status_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время последнего статуса'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='track_number',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Трек-номер должен содержать от 1 до 20 символов (цифры/буквы), без пробелов.', regex='^[0-9A-Za-z]{1,20}$')], verbose_name='Трек-номер'),
        ),
        migrations.CreateModel(
            name='ParcelHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Ожидает поступления на склад в Китае'), (1, 'Принят на склад в Китае'), (2, 'Отправлен из Китая'), (3, 'Прибыл в пункт выдачи'), (4, 'Получен')], verbose_name='Статус')),
                ('message', models.CharField(blank=True, help_text="Например: 'Товар прибыл в пункт выдачи Ош ER-010'", max_length=255, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='main.parcel', verbose_name='Посылка')),
            ],
            options={
                'verbose_name': 'Событие посылки',
                'verbose_name_plural': 'История посылки',
                'ordering': ['-created_at'],
            },
        ),
    ]
