# Generated by Django 5.2.9 on 2025-12-10 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_parcel_description_alter_parcel_last_status_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcel',
            options={'verbose_name': 'Посылка', 'verbose_name_plural': 'Посылки'},
        ),
        migrations.AlterModelOptions(
            name='parcelhistory',
            options={'ordering': ('-created_at',), 'verbose_name': 'История посылки', 'verbose_name_plural': 'История посылок'},
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='last_status_at',
        ),
        migrations.AddField(
            model_name='parcel',
            name='auto_flow_stage',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Этап авто-цепочки'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='auto_flow_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Старт авто-цепочки (Китай)'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='local_flow_stage',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Этап локальной цепочки'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='local_flow_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Старт локальной цепочки (Киргизия)'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ожидает поступления на склад в Китае'), (1, 'Принят на склад в Китае'), (2, 'Отправлен из Китая'), (3, 'Прибыл в пункт выдачи'), (4, 'Получен')], default=0, verbose_name='Текущий статус'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='track_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Трек-номер'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь (если уже привязан)'),
        ),
        migrations.AlterField(
            model_name='parcelhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='parcelhistory',
            name='message',
            field=models.TextField(blank=True, verbose_name='Сообщение'),
        ),
    ]
