# Generated by Django 5.2.9 on 2025-12-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_parcel_options_alter_parcelhistory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='LIDER CARGO', max_length=100, verbose_name='Название проекта')),
                ('logo', models.ImageField(blank=True, help_text='PNG/SVG с логотипом. Если не задан, используется статика img/logo.png', null=True, upload_to='branding/', verbose_name='Логотип')),
                ('bg_light', models.ImageField(blank=True, help_text='Можно GIF или картинку. Используется в светлом режиме.', null=True, upload_to='branding/', verbose_name='Фон (светлая тема)')),
                ('bg_dark', models.ImageField(blank=True, help_text='Можно GIF или картинку. Используется в тёмном режиме.', null=True, upload_to='branding/', verbose_name='Фон (тёмная тема)')),
                ('default_dark_mode', models.BooleanField(default=False, verbose_name='Тёмная тема по умолчанию')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
