# Generated by Django 5.2.9 on 2025-12-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinetprofile',
            name='full_name',
            field=models.CharField(default=1, max_length=255, verbose_name='ФИО'),
            preserve_default=False,
        ),
    ]
