# Generated by Django 5.2.9 on 2025-12-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_cabinetprofile_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinetprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=32, unique=True, verbose_name='Телефон'),
        ),
    ]
