# Generated by Django 5.2.9 on 2025-12-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_cabinetprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='title',
            field=models.CharField(default='kargoexpress', max_length=100, verbose_name='Название проекта'),
        ),
    ]
