# Generated by Django 5.2.9 on 2025-12-29 19:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_pickuppoint_phone_alter_cabinetprofile_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcelhistory',
            options={'ordering': ('-occurred_at', '-id'), 'verbose_name': 'История посылки', 'verbose_name_plural': 'История посылок'},
        ),
        migrations.RemoveIndex(
            model_name='parcelhistory',
            name='main_parcel_parcel__1b7ad1_idx',
        ),
        migrations.AddField(
            model_name='parcelhistory',
            name='occurred_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время события'),
        ),
        migrations.AddIndex(
            model_name='parcelhistory',
            index=models.Index(fields=['parcel', 'occurred_at'], name='main_parcel_parcel__73206c_idx'),
        ),
    ]
