# Generated by Django 5.2.9 on 2025-12-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_sitesettings_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuppoint',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона'),
        ),
    ]
