# Generated by Django 5.2.9 on 2025-12-27 18:14

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_pickuppoint_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinetprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате +<код><номер>, например +996700123456', regex='^\\+\\d{6,15}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Ожидает поступления на склад в Китае'), (1, 'Принят на склад в Китае'), (2, 'Отправлен из Китая'), (3, 'Прибыл в пункт выдачи'), (4, 'Получен')], db_index=True, default=0, verbose_name='Текущий статус'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='track_number',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='Трек-номер может содержать только буквы/цифры и символы . _ -', regex='^[A-Za-z0-9._\\-]{1,64}$')], verbose_name='Трек-номер'),
        ),
        migrations.AlterField(
            model_name='parcelhistory',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Ожидает поступления на склад в Китае'), (1, 'Принят на склад в Китае'), (2, 'Отправлен из Китая'), (3, 'Прибыл в пункт выдачи'), (4, 'Получен')], db_index=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате +<код><номер>, например +996700123456', regex='^\\+\\d{6,15}$')], verbose_name='Номер телефона'),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['created_at'], name='main_parcel_created_ff3ef6_idx'),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['user', 'status'], name='main_parcel_user_id_a08d5a_idx'),
        ),
        migrations.AddIndex(
            model_name='parcelhistory',
            index=models.Index(fields=['parcel', 'created_at'], name='main_parcel_parcel__1b7ad1_idx'),
        ),
        migrations.AddIndex(
            model_name='pickuppoint',
            index=models.Index(fields=['is_active'], name='main_pickup_is_acti_139532_idx'),
        ),
        migrations.AddIndex(
            model_name='pickuppoint',
            index=models.Index(fields=['name'], name='main_pickup_name_2a4e69_idx'),
        ),
        migrations.AddConstraint(
            model_name='cabinetprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('phone__isnull', False), models.Q(('phone', ''), _negated=True)), fields=('phone',), name='uniq_cabinet_phone_not_empty'),
        ),
    ]
