# Generated by Django 5.2.9 on 2026-01-12 18:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_parcelhistory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='parcel',
            name='main_parcel_created_ff3ef6_idx',
        ),
        migrations.AddField(
            model_name='parcelhistory',
            name='message_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='SHA-256 от message для идемпотентности без тяжёлого индекса по TextField.', max_length=64, verbose_name='Хэш сообщения'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='auto_flow_stage',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Этап авто-цепочки'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='auto_flow_started_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Старт авто-цепочки (Китай)'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='local_flow_stage',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Этап локальной цепочки'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='local_flow_started_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Старт локальной цепочки (Киргизия)'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['status', 'auto_flow_stage', 'auto_flow_started_at'], name='main_parcel_status_25b539_idx'),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['status', 'local_flow_stage', 'local_flow_started_at'], name='main_parcel_status_9c1f55_idx'),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(condition=models.Q(('auto_flow_started_at__isnull', False), models.Q(('status', 4), _negated=True)), fields=['id'], name='parcel_auto_flow_active_idx'),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(condition=models.Q(('local_flow_started_at__isnull', False), models.Q(('status', 4), _negated=True)), fields=['id'], name='parcel_local_flow_active_idx'),
        ),
        migrations.AddIndex(
            model_name='parcelhistory',
            index=models.Index(fields=['parcel', 'status', 'occurred_at'], name='main_parcel_parcel__6b6760_idx'),
        ),
    ]
