# Generated by Django 5.2.9 on 2026-01-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_parcel_main_parcel_created_ff3ef6_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='parcelhistory',
            constraint=models.UniqueConstraint(fields=('parcel', 'status', 'occurred_at', 'message_hash'), name='uniq_parcel_history_event_hash'),
        ),
    ]
