# Generated by Django 5.2.9 on 2025-12-27 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_pickuppoint_phone_alter_cabinetprofile_phone_and_more'),
        ('main', '0010_alter_cabinetprofile_phone_alter_parcel_status_and_more'),
    ]

    operations = [
    ]
