# Generated by Django 5.2.9 on 2026-01-14 15:34

import hashlib
from django.db import migrations


def forwards(apps, schema_editor):
    ParcelHistory = apps.get_model("main", "ParcelHistory")

    # 1) Приводим message_hash в консистентное состояние
    qs = (
        ParcelHistory.objects.all()
        .only("id", "message", "message_hash")
        .order_by("id")
    )

    for h in qs.iterator():
        msg = (h.message or "").strip()
        computed = hashlib.sha256(msg.encode("utf-8")).hexdigest() if msg else ""
        if h.message_hash != computed:
            h.message_hash = computed
            h.save(update_fields=["message_hash"])

    # 2) Удаляем дубликаты по будущему UNIQUE ключу
    seen = set()
    to_delete = []

    qs2 = (
        ParcelHistory.objects.all()
        .only("id", "parcel_id", "status", "occurred_at", "message_hash")
        .order_by("id")
    )

    for h in qs2.iterator():
        key = (h.parcel_id, h.status, h.occurred_at, h.message_hash)
        if key in seen:
            to_delete.append(h.id)
        else:
            seen.add(key)

    if to_delete:
        ParcelHistory.objects.filter(id__in=to_delete).delete()


def backwards(apps, schema_editor):
    # Удалённые дубликаты восстановить нельзя.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_remove_parcel_main_parcel_created_ff3ef6_idx_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
