# Generated by Django 5.2.9 on 2026-01-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_parcelhistory_uniq_parcel_history_event_hash'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='parcelhistory',
            constraint=models.UniqueConstraint(fields=('parcel', 'status', 'occurred_at', 'message_hash'), name='uniq_parcel_history_event_hash'),
        ),
    ]
